-- AlterTable
ALTER TABLE "TimeTrack" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "TimeTrack" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
ALTER TABLE "TimeTrack" ADD COLUMN IF NOT EXISTS "manualReason" TEXT;
ALTER TABLE "TimeTrack" ADD COLUMN IF NOT EXISTS "manualStatus" TEXT DEFAULT 'approved';
