"""Phase 9 Schema Changes

Revision ID: 83af565fe624
Revises: a9b8c7d6e5f4
Create Date: 2026-02-10 19:27:52.661666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83af565fe624'
down_revision: Union[str, Sequence[str], None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('plans_name_key'), type_='unique')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('refresh_tokens_token_key'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('education')
        batch_op.drop_column('experience')
        batch_op.drop_column('skills')
        batch_op.drop_column('bio')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('refresh_tokens_token_key'), ['token'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('plans_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
