"""completing_models

Revision ID: d77a2c092c07
Revises: c1a2b3d4e5f6
Create Date: 2026-02-05 20:59:38.346740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd77a2c092c07'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_status_history_id'), ['id'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_constraint(batch_op.f('uq_applications_job_candidate'), type_='unique')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_audit_logs_company_id', 'companies', ['company_id'], ['id'])
        batch_op.drop_column('metadata')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('resume_text', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_candidates_company_id_companies'), type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('validation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('validated_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('doc_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_documents_validated_by', 'users', ['validated_by_user_id'], ['id'])

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'open'"))

    # Preenche valores NULL em plans.price antes de mudar o tipo
    op.execute("UPDATE plans SET price = '0' WHERE price IS NULL")
    
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=40),
               nullable=False)
        batch_op.alter_column('features',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_index(batch_op.f('ix_subscriptions_mp_preapproval_id'))
        batch_op.drop_constraint(batch_op.f('uq_subscriptions_mp_preapproval_id'), type_='unique')
        batch_op.create_foreign_key('fk_subscriptions_company_id', 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscriptions_company_id', type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('uq_subscriptions_mp_preapproval_id'), ['mp_preapproval_id'])
        batch_op.create_index(batch_op.f('ix_subscriptions_mp_preapproval_id'), ['mp_preapproval_id'], unique=1)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_column('company_id')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('features',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.String(length=40),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False,
               existing_server_default=sa.text("'open'"))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_validated_by', type_='foreignkey')
        batch_op.alter_column('doc_type',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('validated_at')
        batch_op.drop_column('validated_by_user_id')
        batch_op.drop_column('validation_reason')
        batch_op.drop_column('status')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_candidates_company_id_companies'), 'companies', ['company_id'], ['id'])
        batch_op.drop_column('resume_text')
        batch_op.drop_column('resume_url')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', sqlite.JSON(), nullable=True))
        batch_op.drop_constraint('fk_audit_logs_company_id', type_='foreignkey')
        batch_op.alter_column('entity_type',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('details')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_applications_job_candidate'), ['job_id', 'candidate_user_id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('application_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_status_history_id'))

    op.drop_table('application_status_history')
    # ### end Alembic commands ###
