"""fix_float_to_numeric

Revision ID: ead2393a58b1
Revises: 83af565fe624
Create Date: 2026-02-13 01:38:46.947175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead2393a58b1'
down_revision: Union[str, Sequence[str], None] = '83af565fe624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('match_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recruiter_notes', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint('fk_applications_candidate_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_applications_company_id_companies', type_='foreignkey')
        batch_op.create_foreign_key('fk_applications_candidate_id_users', 'users', ['candidate_id'], ['id'])
        batch_op.drop_column('score')
        batch_op.drop_column('company_id')
        batch_op.drop_column('candidate_user_id')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parsed_resume', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills_structured', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('behavioral_profile', sa.Text(), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('salary', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('interview_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('match_score_threshold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requirements_structured', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('salary_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('custom_questions', sa.Text(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'open'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint('fk_jobs_company_id_companies', type_='foreignkey')
        batch_op.create_foreign_key('fk_jobs_company_id_users', 'users', ['company_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('brand_logo', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('brand_color_primary', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('brand_color_secondary', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('badges', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('two_factor_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(true)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint('fk_users_active_company', type_='foreignkey')
        batch_op.drop_column('phone')
        batch_op.drop_column('terms_version')
        batch_op.drop_column('terms_accepted_at')
        batch_op.drop_column('name')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('active_company_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_company_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('terms_version', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=30), nullable=True))
        batch_op.create_foreign_key('fk_users_active_company', 'companies', ['active_company_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('two_factor_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(true)'))
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('points')
        batch_op.drop_column('badges')
        batch_op.drop_column('brand_color_secondary')
        batch_op.drop_column('brand_color_primary')
        batch_op.drop_column('brand_logo')
        batch_op.drop_column('company_name')
        batch_op.drop_column('is_active')
        batch_op.drop_column('full_name')
        batch_op.drop_column('hashed_password')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_company_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_jobs_company_id_companies', 'companies', ['company_id'], ['id'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'open'"))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('custom_questions')
        batch_op.drop_column('location_type')
        batch_op.drop_column('salary_max')
        batch_op.drop_column('salary_min')
        batch_op.drop_column('requirements_structured')
        batch_op.drop_column('match_score_threshold')
        batch_op.drop_column('comments')
        batch_op.drop_column('interview_link')
        batch_op.drop_column('type')
        batch_op.drop_column('salary')
        batch_op.drop_column('requirements')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('behavioral_profile')
        batch_op.drop_column('skills_structured')
        batch_op.drop_column('parsed_resume')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('score', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_applications_candidate_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_applications_company_id_companies', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('fk_applications_candidate_user_id_users', 'users', ['candidate_user_id'], ['id'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_column('recruiter_notes')
        batch_op.drop_column('ai_analysis')
        batch_op.drop_column('match_score')
        batch_op.drop_column('candidate_id')

    # ### end Alembic commands ###
