# nginx.conf

# User and group
user nginx;
worker_processes auto;

# Error log
error_log /var/log/nginx/error.log;

# PID file
pid /var/run/nginx.pid;

# Events
events {
    worker_connections 1024;
}

# HTTP Server Configuration
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    gzip on;
    gzip_types text/plain application/json text/css application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Upstream for backend services
    upstream frontend {
        server 127.0.0.1:3000;
    }

    upstream backend {
        server 127.0.0.1:8000;
    }

    # Server
    server {
        listen 80;
        server_name 187.77.49.207;

        location / {
            proxy_pass http://frontend;
        }

        location /api {
            proxy_pass http://backend;
        }
    }
}