CREATE TYPE "CEOOnboardingState" AS ENUM ('INVITED', 'PASSWORD_CHANGE', 'FACE_ENROLLMENT', 'PROFILE_REQUIRED', 'CONTRACT_PENDING', 'ACTIVE');
ALTER TABLE "User" ADD COLUMN "onboardingState" "CEOOnboardingState";
ALTER TABLE "User" ADD COLUMN "onboardingCompletedAt" TIMESTAMP(3);
