ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COMERCIAL';
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "subscriptionStartedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "suspensionReason" TEXT;