"""Add gamification level and current_xp columns

Revision ID: 971fcbcebe40
Revises: aa7b35119d32
Create Date: 2026-03-05 10:35:34.757710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "971fcbcebe40"
down_revision: Union[str, None] = "aa7b35119d32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "read", sa.Boolean(), server_default=sa.text("(false)"), nullable=False
        ),
        sa.Column("link", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "reviews_360",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_user_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_user_id", sa.Integer(), nullable=False),
        sa.Column("relationship", sa.String(length=20), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reviews_360", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reviews_360_id"), ["id"], unique=False)

    op.create_table(
        "kb_articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("tags", sa.String(length=500), nullable=True),
        sa.Column("views", sa.Integer(), nullable=True),
        sa.Column("helpful_votes", sa.Integer(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("kb_articles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kb_articles_id"), ["id"], unique=False)

    op.create_table(
        "killer_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("expected_answer", sa.Text(), nullable=True),
        sa.Column("is_eliminatory", sa.Boolean(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("killer_questions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_killer_questions_id"), ["id"], unique=False
        )

    op.create_table(
        "payslips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("reference_month", sa.String(length=7), nullable=False),
        sa.Column("gross_salary", sa.Float(), nullable=False),
        sa.Column("net_salary", sa.Float(), nullable=False),
        sa.Column("deductions", sa.Float(), nullable=True),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payslips", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payslips_id"), ["id"], unique=False)

    op.create_table(
        "pdi_goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quarter", sa.String(length=10), nullable=False),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pdi_goals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pdi_goals_id"), ["id"], unique=False)

    op.create_table(
        "purchase_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.Column("approver_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("approver_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchase_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_purchase_requests_id"), ["id"], unique=False
        )

    op.create_table(
        "time_bank",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("hours", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("time_bank", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_time_bank_id"), ["id"], unique=False)

    op.create_table(
        "webhook_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("events", sa.String(length=1000), nullable=False),
        sa.Column("secret", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("webhook_subscriptions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_webhook_subscriptions_id"), ["id"], unique=False
        )

    op.create_table(
        "workflow_triggers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("trigger_event", sa.String(length=100), nullable=False),
        sa.Column("trigger_condition", sa.JSON(), nullable=True),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("action_config", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflow_triggers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflow_triggers_id"), ["id"], unique=False
        )

    op.create_table(
        "ticket_ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ticket_ratings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ticket_ratings_id"), ["id"], unique=False)

    with op.batch_alter_table("rh_tickets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rh_tickets_id"))

    op.drop_table("rh_tickets")
    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interviews_id"))

    op.drop_table("interviews")
    with op.batch_alter_table("attendance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("latitude", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("longitude", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("gps_accuracy", sa.Float(), nullable=True))
        batch_op.add_column(
            sa.Column("photo_url", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("device_fingerprint", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("is_verified", sa.String(length=50), nullable=True)
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("trial_expires_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("current_xp", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("level", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("level")
        batch_op.drop_column("current_xp")
        batch_op.drop_column("trial_expires_at")

    with op.batch_alter_table("attendance", schema=None) as batch_op:
        batch_op.drop_column("is_verified")
        batch_op.drop_column("device_fingerprint")
        batch_op.drop_column("photo_url")
        batch_op.drop_column("gps_accuracy")
        batch_op.drop_column("longitude")
        batch_op.drop_column("latitude")

    op.create_table(
        "interviews",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("application_id", sa.INTEGER(), nullable=False),
        sa.Column("candidate_id", sa.INTEGER(), nullable=False),
        sa.Column("interviewer_id", sa.INTEGER(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=50), nullable=True),
        sa.Column("type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("location", sa.VARCHAR(length=100), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("scheduled_date", sa.DATETIME(), nullable=False),
        sa.Column("completed_at", sa.DATETIME(), nullable=True),
        sa.Column("feedback", sa.TEXT(), nullable=True),
        sa.Column("score", sa.FLOAT(), nullable=True),
        sa.Column("recommendation", sa.VARCHAR(length=50), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interviewer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interviews_id"), ["id"], unique=False)

    op.create_table(
        "rh_tickets",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("ticket_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("status", sa.VARCHAR(length=50), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column("receipt_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(now())"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(now())"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rh_tickets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rh_tickets_id"), ["id"], unique=False)

    with op.batch_alter_table("ticket_ratings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ticket_ratings_id"))

    op.drop_table("ticket_ratings")
    with op.batch_alter_table("workflow_triggers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_triggers_id"))

    op.drop_table("workflow_triggers")
    with op.batch_alter_table("webhook_subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webhook_subscriptions_id"))

    op.drop_table("webhook_subscriptions")
    with op.batch_alter_table("time_bank", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_time_bank_id"))

    op.drop_table("time_bank")
    with op.batch_alter_table("purchase_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_requests_id"))

    op.drop_table("purchase_requests")
    with op.batch_alter_table("pdi_goals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pdi_goals_id"))

    op.drop_table("pdi_goals")
    with op.batch_alter_table("payslips", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payslips_id"))

    op.drop_table("payslips")
    with op.batch_alter_table("killer_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_killer_questions_id"))

    op.drop_table("killer_questions")
    with op.batch_alter_table("kb_articles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kb_articles_id"))

    op.drop_table("kb_articles")
    with op.batch_alter_table("reviews_360", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviews_360_id"))

    op.drop_table("reviews_360")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_id"))

    op.drop_table("notifications")
    # ### end Alembic commands ###
