"""rename_mp_to_api

Revision ID: 5a9e5dbefe41
Revises: 971fcbcebe40
Create Date: 2026-03-07 15:58:36.424206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9e5dbefe41'
down_revision: Union[str, None] = '971fcbcebe40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed das_mei changes

    # Removed audit_logs changes

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asaas_subscription_id', sa.String(length=120), nullable=True))
        batch_op.drop_column('mp_preapproval_id')

    # Removed tasks changes

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('current_xp')

    # Removed tasks changes

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mp_preapproval_id', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('asaas_subscription_id')

    # Removed audit_logs changes

    # Removed das_mei changes
    # ### end Alembic commands ###
