"""Add tax_type to Transaction

Revision ID: 5c458c5019a8
Revises: e1501903166b
Create Date: 2026-02-17 00:23:07.179613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c458c5019a8'
down_revision: Union[str, None] = 'e1501903166b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('cep', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('street', sa.String(length=200), nullable=True))
    op.add_column('companies', sa.Column('number', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('complement', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('neighborhood', sa.String(length=100), nullable=True))
    op.add_column('transactions', sa.Column('tax_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'tax_type')
    op.drop_column('companies', 'neighborhood')
    op.drop_column('companies', 'complement')
    op.drop_column('companies', 'number')
    op.drop_column('companies', 'street')
    op.drop_column('companies', 'cep')
    # ### end Alembic commands ###
