"""Add biometric and bank hub fields

Revision ID: aa7b35119d32
Revises: 889116dc378c
Create Date: 2026-03-02 19:39:47.780860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7b35119d32'
down_revision: Union[str, None] = '889116dc378c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('queue', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_tickets_companies', 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('queue')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
        batch_op.drop_column('device_fingerprint')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('gps_accuracy')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###

