"""Add gamification and fix schema

Revision ID: d0346c349405
Revises: 5c458c5019a8
Create Date: 2026-02-23 20:20:58.931183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0346c349405'
down_revision: Union[str, None] = '5c458c5019a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('trigger_action', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missions_id'), ['id'], unique=False)

    op.create_table('user_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_missions_id'), ['id'], unique=False)

    # with op.batch_alter_table('tasks', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('tickets', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
    #     batch_op.add_column(sa.Column('queue', sa.String(length=50), nullable=True))
    #     batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('queue')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('user_missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_missions_id'))

    op.drop_table('user_missions')
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missions_id'))

    op.drop_table('missions')
    # ### end Alembic commands ###
