ALTER TABLE "TimeTrack"
ADD COLUMN "earlyLeaveMinutes" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "TimeClosing"
ADD COLUMN "salaryBase" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "monthlyDivisor" INTEGER NOT NULL DEFAULT 220,
ADD COLUMN "payableWorkdays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "paidRestDays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "hourlyRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "overtime50Value" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "overtime100Value" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "nightShiftValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "dsrHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "absenceMinutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lateMinutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "earlyLeaveMinutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "absenceDiscount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "grossPay" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "inssBase" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "inssDiscount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "irrfBase" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "irrfDiscount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "fgtsBase" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "fgtsAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "netPay" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "calculationVersion" TEXT NOT NULL DEFAULT 'CLT_2026_1',
ADD COLUMN "closedBy" TEXT,
ADD COLUMN "reopenedBy" TEXT;